const API_BEST_URL_DEVELOPMENT = "http://localhost:7102/api/Admin";
const API_BEST_URL_PRODUCTION = "http://appname.azurewebsite.net";

const ENDPOINT = {
    ADD_PRODUCT:'AddProduct',
    UPLOAD_IMAGE: 'UpoladImage',
    POST_CATEGORIES: 'AddCategory',
    POST_DETAILS: 'AddDetailsCategory',
    POST_SIZE_PRODUCT: 'AddSizeProduct',
};

const development = {
    API_URL_ADD_PRODUCT: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.ADD_PRODUCT}`,
    API_URL_UPLOAD_IMAGE: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.UPLOAD_IMAGE}`,
    API_URL_POST_CATEGORY: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.POST_CATEGORIES}`,
    API_URL_POST_DETAILS: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.POST_DETAILS}`,
    API_URL_POST_SIZE_PRODUCT: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.POST_SIZE_PRODUCT}`
};

const predection = {
    API_URL_ADD_PRODUCT: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.ADD_PRODUCT}`,
    API_URL_UPLOAD_IMAGE: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.UPLOAD_IMAGE}`,
    API_URL_POST_CATEGORY: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.POST_CATEGORIES}`,
    API_URL_POST_DETAILS: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.POST_DETAILS}`,
    API_URL_POST_SIZE_PRODUCT: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.POST_SIZE_PRODUCT}`

};

const urlAdmin = process.env.NODE_ENV === 'development' ? development : predection;

export default urlAdmin;