const API_BEST_URL_DEVELOPMENT = "http://localhost:7102/api/Product";
const API_BEST_URL_PRODUCTION = "http://appname.azurewebsite.net";

const ENDPOINT = {
    GETALL_DATA:'GetProducts',
    GET_BY_ID_PRODUCT: 'GetProductbyId',
    GET_BY_ID_IMAGE: 'GetImageById',
    GET_BY_ID_DETAIL: 'GetProductsByDetail',
};

const development = {
    API_URL_GET_ALL_PRODUCTS: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.GETALL_DATA}`,
    API_URL_GET_IMAGE_BY_ID: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.GET_BY_ID_IMAGE}`,
    API_URL_GET_BY_ID_PRODUCT: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.GET_BY_ID_PRODUCT}`,
    API_URL_GET_BY_ID_DETAIL: `${API_BEST_URL_DEVELOPMENT}/${ENDPOINT.GET_BY_ID_DETAIL}`
};

const predection = {
    API_URL_GET_ALL_PRODUCTS: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.GETALL_DATA}`,
    API_URL_GET_IMAGE_BY_ID: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.GET_BY_ID_IMAGE}`,
    API_URL_GET_BY_ID_PRODUCT: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.GET_BY_ID_PRODUCT}`,
    API_URL_GET_BY_ID_DETAIL: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.GET_BY_ID_DETAIL}`
    // API_URL_POST_DATA: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.POST_DATA}`,
    // API_URL_UPDATE: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.UPDATE}`,
    // API_URL_DELETE: `${API_BEST_URL_PRODUCTION}/${ENDPOINT.DELETE}`,
};

const urlProduct = process.env.NODE_ENV === 'development' ? development : predection;

export default urlProduct;